spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000

  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB

server:
  forward-headers-strategy: framework

logging:
  level:
    p6spy: info
    org:
      hibernate: info
      springframework: debug

decorator:
  datasource:
    p6spy:
      enable-logging: true
management:
  endpoints:
    web:
      base-path: /keeper-metrics
      exposure:
        include: prometheus
