package com.keeper.homepage.domain.vote.entity;

import static jakarta.persistence.FetchType.LAZY;
import static java.util.UUID.randomUUID;
import static lombok.AccessLevel.PROTECTED;
import static org.hibernate.annotations.OnDeleteAction.CASCADE;
import static org.hibernate.annotations.OnDeleteAction.RESTRICT;
import static org.hibernate.generator.EventType.INSERT;
import static org.hibernate.generator.EventType.UPDATE;

import com.keeper.homepage.domain.member.entity.Member;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.ForeignKey;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PostLoad;
import jakarta.persistence.PostPersist;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import jakarta.persistence.UniqueConstraint;
import java.util.UUID;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.Comment;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.Generated;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.OnDelete;
import org.hibernate.type.SqlTypes;
import org.springframework.data.domain.Persistable;

@DynamicInsert
@DynamicUpdate
@Getter
@Entity
@NoArgsConstructor(access = PROTECTED)
@Table(name = "vote_participation",
    indexes = {
        @Index(name = "idx_vote_participation_vote", columnList = "vote_id"),
        @Index(name = "idx_vote_participation_member", columnList = "member_id")
    },
    uniqueConstraints = @UniqueConstraint(name = "uq_vote_participation_vote_member",
        columnNames = {"vote_id", "dedup_member_id"}))
public class VoteParticipation implements Persistable<UUID> {

  private static final int MAX_VOTER_NAME_LENGTH = 100;

  @Id
  @JdbcTypeCode(SqlTypes.BINARY)
  @Comment("UUID v4 generated by the application")
  @Column(name = "id", nullable = false, updatable = false, columnDefinition = "BINARY(16)")
  private UUID id;

  @ManyToOne(fetch = LAZY)
  @OnDelete(action = CASCADE)
  @JoinColumn(name = "vote_id", nullable = false, columnDefinition = "INT",
      foreignKey = @ForeignKey(name = "fk_vote_participation_vote"))
  private Vote vote;

  @ManyToOne(fetch = LAZY)
  @OnDelete(action = RESTRICT)
  @JoinColumn(name = "member_id", nullable = false, columnDefinition = "INT",
      foreignKey = @ForeignKey(name = "fk_vote_participation_member"))
  private Member member;

  @Generated(event = {INSERT, UPDATE})
  @Column(name = "dedup_member_id", insertable = false, updatable = false,
      columnDefinition = "INT GENERATED ALWAYS AS (NULLIF(member_id, 1)) STORED")
  private Long dedupMemberId;

  @Column(name = "voter_name_snapshot", nullable = false, length = MAX_VOTER_NAME_LENGTH)
  private String voterNameSnapshot;

  @Column(name = "voter_generation_snapshot", nullable = false)
  private Float voterGenerationSnapshot;

  @Transient
  private boolean newEntity = true;

  @Builder
  private VoteParticipation(Vote vote, Member member, String voterNameSnapshot,
      Float voterGenerationSnapshot) {
    this.id = randomUUID();
    this.vote = vote;
    this.member = member;
    this.voterNameSnapshot = voterNameSnapshot;
    this.voterGenerationSnapshot = voterGenerationSnapshot;
  }

  @Override
  public boolean isNew() {
    return newEntity;
  }

  @PostLoad
  @PostPersist
  private void markNotNew() {
    this.newEntity = false;
  }
}
