package com.keeper.homepage.domain.vote.entity;

import static jakarta.persistence.FetchType.LAZY;
import static lombok.AccessLevel.PROTECTED;
import static org.hibernate.annotations.OnDeleteAction.CASCADE;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.ForeignKey;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.Comment;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.OnDelete;
import org.hibernate.type.SqlTypes;

@DynamicInsert
@DynamicUpdate
@Getter
@Entity
@NoArgsConstructor(access = PROTECTED)
@Table(name = "vote_receipt",
    indexes = @Index(name = "idx_vote_receipt_vote", columnList = "vote_id"))
public class VoteReceipt {

  @Id
  @JdbcTypeCode(SqlTypes.BINARY)
  @Comment("UUID v4 generated by the application (web client)")
  @Column(name = "token", nullable = false, updatable = false, columnDefinition = "BINARY(16)")
  private UUID token;

  @ManyToOne(fetch = LAZY)
  @OnDelete(action = CASCADE)
  @JoinColumn(name = "vote_id", nullable = false, columnDefinition = "INT",
      foreignKey = @ForeignKey(name = "fk_vote_receipt_vote"))
  private Vote vote;

  @OneToMany(mappedBy = "receipt")
  private final List<VoteChoice> choices = new ArrayList<>();

  @Builder
  private VoteReceipt(UUID token, Vote vote) {
    this.token = token;
    this.vote = vote;
  }
}
