package com.keeper.homepage.domain.vote.entity;

import static jakarta.persistence.FetchType.LAZY;
import static java.util.UUID.randomUUID;
import static lombok.AccessLevel.PROTECTED;
import static org.hibernate.annotations.OnDeleteAction.CASCADE;
import static org.hibernate.generator.EventType.INSERT;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.ForeignKey;
import jakarta.persistence.Id;
import jakarta.persistence.Index;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.PostLoad;
import jakarta.persistence.PostPersist;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.ColumnDefault;
import org.hibernate.annotations.Comment;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.Generated;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.annotations.OnDelete;
import org.hibernate.type.SqlTypes;
import org.springframework.data.domain.Persistable;

@DynamicInsert
@DynamicUpdate
@Getter
@Entity
@NoArgsConstructor(access = PROTECTED)
@Table(name = "vote_receipt",
    indexes = @Index(name = "idx_vote_receipt_vote", columnList = "vote_id"))
public class VoteReceipt implements Persistable<UUID> {

  @Id
  @JdbcTypeCode(SqlTypes.BINARY)
  @Comment("UUID v4 generated by the application server")
  @Column(name = "token", nullable = false, updatable = false, columnDefinition = "BINARY(16)")
  private UUID token;

  @ManyToOne(fetch = LAZY)
  @OnDelete(action = CASCADE)
  @JoinColumn(name = "vote_id", nullable = false, columnDefinition = "INT",
      foreignKey = @ForeignKey(name = "fk_vote_receipt_vote"))
  private Vote vote;

  @OneToMany(mappedBy = "receipt")
  private final List<VoteChoice> choices = new ArrayList<>();

  @Generated(event = INSERT)
  @ColumnDefault("CURRENT_TIMESTAMP(6)")
  @Column(name = "created_at", nullable = false, insertable = false, updatable = false,
      columnDefinition = "DATETIME(6)")
  private LocalDateTime createdAt;

  @Transient
  private boolean newEntity = true;

  @Builder
  private VoteReceipt(Vote vote) {
    this.token = randomUUID();
    this.vote = vote;
  }

  @Override
  public UUID getId() {
    return token;
  }

  @Override
  public boolean isNew() {
    return newEntity;
  }

  @PostLoad
  @PostPersist
  private void markNotNew() {
    this.newEntity = false;
  }
}
